default: &default
  adapter: mysql2
  database: blog_dev
  pool: 5
  host: localhost
  enconding: utf8
  username: root
  password: 
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: blog_test

production:
  <<: *default
